请问B.shape的值是多少?

In [2]:
import numpy as np

A = np.random.randn(4, 3)
print(A)
B = np.sum(A, axis=1, keepdims=True)
print(B)
print(B.shape)

[[-0.5771457   0.56908187  0.40496354]
 [ 0.31571351  1.26269903  0.33956045]
 [ 0.2214815   0.61329401  0.4958941 ]
 [ 0.44433857  0.03982008 -0.74582244]]
[[ 0.3968997 ]
 [ 1.91797299]
 [ 1.3306696 ]
 [-0.26166379]]
(4, 1)


当3个神经元的权重初始化为0时，它们会始终保持相同的行为，无法学出不同的特征。

In [16]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

# 输入数据 X: (2, 2)，2维输入，有2个样本
X = np.array([[1, 2],
              [3, 4]])  # shape = (2, 2)

# 真实标签 Y: 3个神经元 × 2个样本
Y = np.array([[1, 0],
              [0, 1],
              [1, 0]])  # shape = (3, 2)

# 初始化权重和偏置，全为0
W = np.zeros((3, 2))  # 3个神经元，每个2个输入特征
b = np.zeros((3, 1))  # 每个神经元一个偏置项

# 前向传播
Z = np.dot(W, X) + b        # shape = (3, 2)
A = sigmoid(Z)              # shape = (3, 2)

# 计算损失（MSE）
loss = np.mean((A - Y) ** 2)

# 反向传播（MSE对sigmoid输出求导）
dA = 2 * (A - Y) / Y.shape[1]  # 均方误差梯度

# sigmoid 的导数
dZ = dA * A * (1 - A)

# 计算梯度
dW = np.dot(dZ, X.T) / X.shape[1]
db = np.sum(dZ, axis=1, keepdims=True) / X.shape[1]

# 更新参数
learning_rate = 0.1
W = W - learning_rate * dW
b = b - learning_rate * db

# 输出每个神经元的权重和偏置
for i in range(3):
    print(f"神经元{i+1}：W = {W[i]}, b = {b[i][0]}")


神经元1：W = [-0.00625 -0.00625], b = 0.0
神经元2：W = [0.00625 0.00625], b = 0.0
神经元3：W = [-0.00625 -0.00625], b = 0.0
