python例题：假设img是一个（32,32,3）数组，具有3个颜色通道：红色、绿色和蓝色的32x32像素的图像。 如何将其重新转换为列向量？

In [1]:
import numpy as np

img = np.random.rand(32, 32, 3)

print("img.shape:\n")
print(img)
print(img.shape)

x = img.reshape(-1, 1) # -1 是 NumPy 的一种“自动推理维度”的写法，会根据剩下的维度自动计算出具体数值。
y = img.reshape((32*32*3), 1)

print(x)
print(y)

print(x.shape) # (3072, 1)
print(y.shape) # (3072, 1)

img.shape:

[[[0.93108586 0.98644105 0.24267648]
  [0.76848368 0.6482555  0.96970323]
  [0.15736172 0.29367609 0.78207409]
  ...
  [0.51672923 0.70970795 0.1614867 ]
  [0.05616228 0.32448366 0.85955277]
  [0.34416619 0.45183893 0.28448043]]

 [[0.54411489 0.77418213 0.33884808]
  [0.58730861 0.69547878 0.97136125]
  [0.52440764 0.5380534  0.19132048]
  ...
  [0.62791048 0.42441407 0.41043147]
  [0.7103122  0.9180599  0.52064108]
  [0.13839852 0.01880304 0.80938833]]

 [[0.61940023 0.27125994 0.33781494]
  [0.16315816 0.2721826  0.08406606]
  [0.31135322 0.05886127 0.86888544]
  ...
  [0.41962173 0.59213097 0.77808779]
  [0.92669087 0.44000967 0.29552375]
  [0.49597876 0.77458271 0.36142683]]

 ...

 [[0.16736142 0.86597752 0.82003603]
  [0.41929249 0.99517427 0.95518786]
  [0.61073066 0.18717949 0.6586643 ]
  ...
  [0.77840569 0.48316815 0.55404436]
  [0.32771281 0.29161963 0.96680485]
  [0.76065064 0.86267799 0.08233498]]

 [[0.7596737  0.11113098 0.09484285]
  [0.2278857  0.42874294 

请问数组“c”的维度是多少？

In [2]:
import numpy as np

a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

print(a)
print(b)
print(c)
print(c.shape) # (2, 3)

[[-1.14258654 -0.53590795 -1.68754496]
 [ 0.68673271 -0.42278171  0.05834216]]
[[ 0.08697531]
 [-2.48180022]]
[[-1.05561123 -0.44893264 -1.60056965]
 [-1.79506751 -2.90458193 -2.42345806]]
(2, 3)


看一下下面的这两个随机数组“a”和“b”：

请问c的维度是多少？

In [20]:
import numpy as np

a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a, b)
# d = a * b  报错，元素级乘法需要矩阵形状相同

print(c)
print(c.shape)
# print(d)
# print(d.shape)

[[  4.12369244  -6.11866816 -13.05782046 ... -16.68569006 -11.45628969
    5.08086693]
 [ 23.67795819   7.4656922   -2.70606595 ...   5.10015081   5.90426035
    3.23894615]
 [  7.28551852 -10.71712379   3.835098   ... -14.83249022 -12.24221791
    6.03158656]
 ...
 [  4.17056647 -10.33218488   1.95110748 ... -17.50405111  17.98188441
   -3.32142373]
 [  2.04265461   7.61321426   9.17776208 ...  17.44847842  14.79226667
   -3.54149307]
 [  5.08103436   5.36217651  -6.33908323 ... -15.93721166   3.24553245
    4.80992359]]
(12288, 45)


看一下下面的这个代码片段，请问要怎么把它们向量化？

In [ ]:

# a.shape = (3,4)


# b.shape = (4,1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

In [36]:
import numpy as np

a = np.random.randn(3, 4)
b = np.random.randn(4, 1)
c = a + b.T

print(c)

[[ 0.29940494 -1.21798963 -0.86777857 -0.37279246]
 [ 0.97868251 -2.58093547  0.03377586  1.21291908]
 [-1.09958456 -1.56796004 -1.77700826  2.94804188]]


看一下下面的代码,请问c的维度会是多少？

这将会使用广播机制，b会被复制三次，就会变成(3,3)，再使用元素乘法。所以： c.shape = (3, 3).

In [37]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a * b

print(c)

[[ 0.11393996 -0.04609944 -0.04728719]
 [ 0.77573494  1.14429892  0.5162659 ]
 [-3.70395844 -0.00828866  3.1019801 ]]
